# Step 1: Build stage
FROM node:18.16.0-alpine3.18 AS build-stage
RUN addgroup app && adduser -S -G app app
USER app
WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# # Step 2: Production stage
FROM nginx:1.25.2 AS production-stage

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY nginx.config /etc/nginx/conf.d/default.conf

EXPOSE 3000
ENTRYPOINT ["nginx", "-g", "daemon off;"]
